# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2e84a68085c2c9ca1c4acf16803d6a4c"
application_url = "https://example.com/"
embedded = true
name = "s2s"
handle = "s2s-3"

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-01"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[pos]
embedded = false
